### ISSUE TITLE
error with dropbox

### ISSUE THREAD

**Issue by emans841** [fbctf/cromos#1]
i get this error when i tried to put drop box token 
The extension has already been downloaded
Traceback (most recent call last):
  File "cromos.py", line 75, in <module>
    main()
  File "cromos.py", line 70, in main
    Build(extension, builds, token).builder()
  File "/root/Desktop/cromos/libs/build.py", line 66, in builder
    paths = Drive(self.extension, self.filetype, self.token).ShareLinks()
  File "/root/Desktop/cromos/libs/drive.py", line 158, in ShareLinks
    paths = self.drive.files_list_folder("/{}".format(self.extension))
  File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 715, in files_list_folder
    None,
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 581, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 307, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 157, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 97, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 130, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.

**Comment by fbctf** [comment]
Hi, try again. Probably a connection time error
